# For Node 1 
node1_make: 
	make -f node1.mk 

node1_flash: 
	make flash -f node1.mk 

node1_clean: 
	make clean -f node1.mk 

node1_fuse: 
	make fuse -f node1.mk 

# For Node 2 
node2_make:
	make -f node2.mk 

node2_flash:
	make flash -f node2.mk 

node2_clean: 
	make clean -f node2.mk

node2_fuse: 
	make fuse -f node1.mk 

# For Node 3 
node3_make:
	make -f node3.mk 

node3_flash:
	make flash -f node3.mk 

node3_clean: 
	make clean -f node3.mk

node3_fuse: 
	make fuse -f node1.mk 