node1_make: 
	# make -f node1.mkNOode1s1
	make -f node1.mk 

node1_flash: 
	# make -f node1.mk
	# make flash -f node1.mk 
	make flash -f node1.mk 

node1_clean: 
	# make -f node1.mk
	make clean -f node1.mk 

node2_make:
	# make -f node2.mk
	make -f node2.mk 

node2_flash:
	# make flash -f node2.mk
	make flash -f node2.mk 

node2_clean: 
	make clean -f node2.mk